### ISSUE TITLE
executesql not working

### ISSUE THREAD

**Issue by MrMegamind** [bangonkali/meteor-sqlite-cordova#1]
Hi
when i use this plugins and test it under android the db is created but when i run the create table command it does not work. the error object is as following:

I20160205-14:30:32.169(5)? { db: 
I20160205-14:30:32.170(5)?    { openargs: { name: 'my1.db', dblocation: 'docs' },
I20160205-14:30:32.170(5)?      dbname: 'my1.db' },
I20160205-14:30:32.170(5)?   txlock: true,
I20160205-14:30:32.170(5)?   readOnly: false,
I20160205-14:30:32.170(5)?   executes: [] }

i am using this code to create db and table

```
db = window.sqlitePlugin.openDatabase({name: "my1.db"});
    db.transaction(function(tx) {
        tx.executeSql(
            'CREATE TABLE IF NOT EXISTS smsq (smsname text, smsnumber text, smsmsg text, cstatus integer)',
            function(){
                console.log("tbl created")
            },
            function(e){
                console.log("error in tbal create " + e);
                Meteor.call('sdebug',e)
            }
        );
    });
```

any help is appreciated. thank you

**Comment by bangonkali** [comment]
I will test this when I get the chance. Thanks for following up.

**Comment by MrMegamind** [comment]
hey buddy thanks for the feedback, i was doing the mistake on my side so found the fix, please close this issue

```
    db.transaction(function(tx) {
        //tx.executeSql('DROP TABLE IF EXISTS smsq');
        tx.executeSql(
            'CREATE TABLE IF NOT EXISTS smsq (smsname text, smsnumber text, smsmsg text, cstatus integer)',
               [],
                function(tx, res){
                    Meteor.call('sdebug',"Table Created")
                },
                function(tx, err){
                    Meteor.call('sdebug',"error in creating table " + err.message)
                    Meteor.call('sdebug',err)
                }
        );
    });
```
